author: {avatar: /assets/img/logo_jb_boucle.gif, bio: "Co-g\xE9rant de l'agence de\
    \ r\xE9f\xE9rencement naturel <a href=\"https://www.indixit.com\" target=\"_blank\"\
    >@indixit</a> depuis 2008. Intervenant professionnel et formateur. Papa surfeur\
    \ \xE9picurien ascendant geek.", email: jb@joanny.org, facebook: jeanbaptiste.joanny,
  github: indixit_jb, name: Jean-Baptiste Joanny, twitter: indixit_jb, username: joannyjb}
baseurl: null
collections:
  posts: {output: true}
defaults:
- scope: {path: ''}
  values: {comments: false, layout: post}
description: "Consultant, chef d'entreprise et intervenant professionnel en r\xE9\
  f\xE9rencement naturel, marketing web et digitalisation depuis 2008."
exclude: [CNAME, Gemfile, Gemfile.lock, LICENSE, CHANGELOG.md, README.md, node_modules,
  CODE_OF_CONDUCT.md, CONTRIBUTING.md, lighthouse.png, klise-*.gem, klise.gemspec]
fb_appid: null
google_analytics: null
highlighter: rouge
image: assets/img/ogp.png
include: [_redirects, .htaccess]
jekyll_compose:
  draft_default_front_matter:
    description: null
    modified: null
    tags: []
  post_default_front_matter:
    description: null
    modified: null
    tags: []
kramdown: {syntax_highlighter: rouge}
lang: fr_FR
markdown: kramdown
mode: light
number_of_posts: 10
permalink: /:title/
plugins: [jekyll-feed, jekyll-sitemap, jekyll-postfiles]
repo: null
sass: {style: compressed}
timezone: Europe/Paris
title: Jb Joanny / Expert marketing web & SEO guru
url: https://www.joanny.org
